---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install build-essential and git
  ansible.builtin.apt:
    name:
      - build-essential
      - git
    state: present
  become: yes

- name: Install Homebrew
  ansible.builtin.shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/brew

- name: Set Homebrew environment
  ansible.builtin.shell: |
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  args:
    executable: /bin/bash

- name: Install gcc and k9s using Homebrew
  ansible.builtin.shell: |
    brew doctor
    brew install gcc
    brew install derailed/k9s/k9s
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"
