---
- name: Deploy Ceph CSI RBD on Kubernetes Masters
  hosts: localhost
  vars:
    csi_driver_version: "latest"
    csi_driver_repo: "https://github.com/ceph/ceph-csi.git"
    csi_rbd_yaml: "csi-rbd.yaml"
  roles:
    - ceph_csi_setup
