- name: Add NVIDIA Helm Repository
  command: helm repo add nvidia https://helm.ngc.nvidia.com/nvidia
  register: helm_repo_add_result
  ignore_errors: yes

- name: Update Helm repository cache
  command: /usr/local/bin/helm repo update

- name: Install GPU Operator
  command: helm install --wait --generate-name -n gpu-operator --create-namespace nvidia/gpu-operator --set driver.enabled=false --set toolkit.enabled=false
# k3s requires driver on host
  #command: helm install --wait --generate-name -n gpu-operator --create-namespace nvidia/gpu-operator
