---
- name: Ensure the Kubernetes Python library is installed
  ansible.builtin.command:
    cmd: /usr/bin/python3 -m pip install kubernetes
  become: true

- name: Add Rancher Helm repository
  kubernetes.core.helm_repository:
    name: rancher-latest
    repo_url: https://releases.rancher.com/server-charts/latest
    state: present

- name: Create namespace cattle-system for Rancher
  kubernetes.core.k8s:
    name: cattle-system
    kind: Namespace
    state: present

- name: Add Jetstack Helm repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
    state: present

- name: Update Helm repository cache
  command: /usr/local/bin/helm repo update

- name: Install cert-manager Helm chart
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    values:
      installCRDs: true

- name: Install Rancher from Helm chart
  kubernetes.core.helm:
    name: rancher
    chart_ref: rancher-latest/rancher
    release_namespace: cattle-system
    values:
      hostname: rancher.lan
      bootstrapPassword: admin

- name: Check rollout status of Rancher deployment
  command: kubectl -n cattle-system rollout status deploy/rancher
